from .Clientes import Clientes as ClientesResource
from .Clientes import Cliente as ClienteResource
from .Usuarios import Usuarios as UsuariosResource
from .Usuarios import Usuario as UsuarioResource
from .Productos import Productos as ProductosResource
from .Productos import Producto as ProductoResource
from .Compras import Compras as ComprasResource
from .Compras import Compra as CompraResource
from .ProductosCompras import ProductosCompras as ProductosComprasResource
from .ProductosCompras import ProductoCompra as ProductoCompraResource
